//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CBEntities : DbContext
    {
        public CBEntities()
            : base("name=CBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activities> Activities { get; set; }
        public virtual DbSet<BackManager> BackManager { get; set; }
        public virtual DbSet<ClubLeader> ClubLeader { get; set; }
        public virtual DbSet<Clubs> Clubs { get; set; }
        public virtual DbSet<LearnMore> LearnMore { get; set; }
        public virtual DbSet<MainInfo> MainInfo { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<RegisteClub> RegisteClub { get; set; }
    }
}
