//------------------------------------------------------------------------------
// <auto-generated>
//     姝や唬鐮佸凡浠庢ā鏉跨敓鎴愩€?
//
//     鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳藉鑷村簲鐢ㄧ▼搴忓嚭鐜版剰澶栫殑琛屼负銆?
//     濡傛灉閲嶆柊鐢熸垚浠ｇ爜锛屽皢瑕嗙洊瀵规鏂囦欢鐨勬墜鍔ㄦ洿鏀广€?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public Notice()
        {
            Subtime = DateTime.Now;
            Delflag = 0;
        }

        public int ID { get; set; }
        public string Ncontent { get; set; }
        public Nullable<System.DateTime> Subtime { get; set; }
        public Nullable<short> Delflag { get; set; }
        public Nullable<int> CID { get; set; }
    
        public virtual Clubs Clubs { get; set; }
    }
}
